package me.hejl.image.jpeg;

import static me.hejl.image.TestImages.boxAverage;
import static me.hejl.image.TestImages.bytes;
import static me.hejl.image.TestImages.crop;
import static me.hejl.image.TestImages.grey;
import static me.hejl.image.TestImages.psnr;
import static me.hejl.image.TestImages.readPnm;
import static me.hejl.image.TestImages.resource;
import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.util.Arrays;
import me.hejl.image.Image;
import me.hejl.image.ImageBuilder;
import me.hejl.image.ImageException;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;
import org.junit.jupiter.params.provider.ValueSource;

/**
 * Decodes the images generated by {@code src/test/fixtures/make-jpeg-fixtures.sh} and compares them with the
 * picture they were made from. The images are encoded at quality 95, so they come out close to it, while any
 * mistake in decoding gives a very different picture. {@code DjpegTest} compares more closely with libjpeg.
 */
class JpegReaderTest {

    static final String[] COLOUR = {
        "baseline-420.jpg",
        "baseline-444.jpg",
        "baseline-422.jpg",
        "baseline-440.jpg",
        "baseline-411.jpg",
        "baseline-mixed.jpg",
        "optimized.jpg",
        "restart-rows.jpg",
        "restart-blocks.jpg",
        "rgb.jpg",
        "progressive-420.jpg",
        "progressive-444.jpg",
        "progressive-restart.jpg",
        "sequential-scans.jpg",
        "cmyk.jpg"
    };

    static Image source() throws IOException {
        return readPnm(resource("jpeg/source.ppm"));
    }

    static Image decode(byte[] data, int eighths) throws IOException {
        ImageBuilder builder = new ImageBuilder();
        new JpegReader(new ByteArrayInputStream(data)).decode(builder, eighths);
        return builder.image();
    }

    static Image decode(String name, int eighths) throws IOException {
        return decode(bytes("jpeg/" + name), eighths);
    }

    static String[] colour() {
        return COLOUR;
    }

    @ParameterizedTest
    @MethodSource("colour")
    void decodesColourImages(String name) throws IOException {
        checkDecoding(name, source());
    }

    @ParameterizedTest
    @ValueSource(strings = {"grey.jpg", "grey-progressive.jpg"})
    void decodesGreyImages(String name) throws IOException {
        checkDecoding(name, grey(source()));
    }

    // Full size is compared with the picture the image was made from; the sharp coloured lines in it lose
    // detail to chroma subsampling, hence the low limit. Reduced sizes must equal the full-size result
    // averaged over blocks, up to rounding.
    private static void checkDecoding(String name, Image source) throws IOException {
        Image full = decode(name, 8);
        double psnr = psnr(full, source);
        assertTrue(psnr > 23, name + ": " + psnr + " dB");
        for (int eighths : new int[] {4, 2, 1}) {
            psnr = psnr(decode(name, eighths), boxAverage(full, eighths));
            // Averaging before or after clipping colours to 0–255 differs a little for saturated colours, more so
            // after converting CMYK, which multiplies.
            double limit = dcOnly(name, eighths) ? 20 : name.startsWith("cmyk") ? 30 : 35;
            assertTrue(psnr > limit, name + " at " + eighths + "/8: " + psnr + " dB");
        }
    }

    /**
     * Whether the image is decoded from its DC coefficients alone at this size: images that are held in memory
     * until the last scan, at 1/8. Subsampled colour then has one value per 16 pixels.
     */
    static boolean dcOnly(String name, int eighths) {
        return eighths == 1 && (name.contains("progressive") || name.startsWith("sequential-scans"));
    }

    @Test
    void readsHeader() throws IOException {
        JpegInfo info = new JpegReader(resource("jpeg/progressive-420.jpg")).header();
        assertEquals(new JpegInfo(67, 51, 3, true, 1), info);
        assertEquals(new JpegInfo(67, 51, 1, false, 1), new JpegReader(resource("jpeg/grey.jpg")).header());
        assertEquals(4, new JpegReader(resource("jpeg/cmyk.jpg")).header().components());
    }

    @Test
    void readsExifOrientation() throws IOException {
        assertEquals(
                6, new JpegReader(resource("jpeg/orientation-6.jpg")).header().orientation());
        Image stored = decode("orientation-6.jpg", 8);
        Image shown = stored.oriented(6);
        assertEquals(51, shown.width());
        assertEquals(67, shown.height());
    }

    @ParameterizedTest
    @ValueSource(strings = {"arithmetic.jpg", "precision-12.jpg"})
    void rejectsUnsupportedImages(String name) {
        ImageException e = assertThrows(ImageException.class, () -> new JpegReader(resource("jpeg/" + name)).header());
        assertTrue(e.unsupported(), e.getMessage());
    }

    @Test
    void rejectsOtherFormats() {
        ImageException e =
                assertThrows(ImageException.class, () -> new JpegReader(resource("jpeg/source.ppm")).header());
        assertFalse(e.unsupported());
    }

    @Test
    void rejectsImagesAboveLimit() {
        ImageException e = assertThrows(
                ImageException.class,
                () -> new JpegReader(resource("jpeg/baseline-420.jpg"), 67 * 50, JpegReader.MAX_MEMORY).header());
        assertTrue(e.unsupported());
    }

    @ParameterizedTest
    @ValueSource(strings = {"baseline-420.jpg", "progressive-420.jpg", "restart-blocks.jpg"})
    void decodesTruncatedImages(String name) throws IOException {
        byte[] data = bytes("jpeg/" + name);
        Image image = decode(Arrays.copyOf(data, data.length * 2 / 3), 8);
        assertEquals(67, image.width());
        assertEquals(51, image.height());
        // The top part of sequential images is complete.
        if (!name.startsWith("progressive")) {
            Image top = crop(image, 0, 0, 67, 16);
            assertEquals(Double.POSITIVE_INFINITY, psnr(top, crop(decode(name, 8), 0, 0, 67, 16)));
        }
    }

    @ParameterizedTest
    @ValueSource(strings = {"baseline-420.jpg", "progressive-420.jpg", "sequential-scans.jpg"})
    void decodesArea(String name) throws IOException {
        for (int eighths : new int[] {8, 2}) {
            Image whole = decode(name, eighths);
            ImageBuilder builder = new ImageBuilder();
            new JpegReader(resource("jpeg/" + name)).decode(builder, eighths, 20, 16, 32, 24);
            Image area = builder.image();
            int scale = 8 / eighths;
            Image expected = crop(whole, 20 / scale, 16 / scale, 32 / scale, 24 / scale);
            assertArrayEquals(expected.rgb(), area.rgb(), name + " at " + eighths + "/8");
        }
    }

    @Test
    void clipsAreaToImage() throws IOException {
        ImageBuilder builder = new ImageBuilder();
        new JpegReader(resource("jpeg/baseline-420.jpg")).decode(builder, 8, 60, 40, 100, 100);
        assertEquals(7, builder.image().width());
        assertEquals(11, builder.image().height());
    }

    @Test
    void decodesLargeProgressiveImagesAtOneEighth() throws IOException {
        // All coefficients would need 67×51 → 9×7 MCUs × 6 blocks × 128 bytes; only DC fits.
        ImageBuilder builder = new ImageBuilder();
        new JpegReader(resource("jpeg/progressive-420.jpg"), JpegReader.MAX_PIXELS, 1000).decode(builder, 8);
        Image image = builder.image();
        assertEquals(9, image.width());
        assertEquals(7, image.height());
        assertTrue(psnr(image, boxAverage(decode("progressive-420.jpg", 8), 1)) > 20);
    }

    @Test
    void choosesScale() {
        assertEquals(1, JpegReader.eighths(4000, 3000, 400, 300));
        assertEquals(2, JpegReader.eighths(4000, 3000, 400, 400));
        assertEquals(2, JpegReader.eighths(4000, 3000, 400, 700));
        assertEquals(8, JpegReader.eighths(300, 200, 400, 400));
        assertEquals(4, JpegReader.eighths(800, 600, 400, 300));
    }
}
